export const LOCALSTORAGEKEYS = Object.freeze({
    AUTHENTICATIONTOKEN: 'AUTHENTICATIONTOKEN',
    USERROLE: 'USERROLE',
    USERNAME: 'USERNAME',
    SELECTEDFIRM: 'SELECTEDFIRM',
    ISFROMMAIN: 'ISFROMMAIN'
});
